# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
    config.vm.box = "precise32"
    config.vm.box_url = "http://files.vagrantup.com/precise32.box"
    config.vm.network :hostonly, "192.168.33.10"
    config.vm.share_folder("v-root", "/srv/www/{{ cookiecutter.project_name }}/vagrant/{{ cookiecutter.project_name }}", "../src/{{ cookiecutter.project_name }}")
end
